### ISSUE TITLE
Crash with ifort 19.0.2

### ISSUE THREAD

**Issue by jacobwilliams** [princemahajan/FLINT#1]
I've gotten it to work with fortran 9.1.0, but with ifort 19.0.2.184 20190117 I get:

```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
test               0000000104323774  Unknown               Unknown  Unknown
libsystem_platfor  00007FFF6A88EB5D  Unknown               Unknown  Unknown
test               00000001042AB90A  _erk.erkintegrate         577  ERKIntegrate.f90
test               000000010429D80E  _erk_mp_erk_int_          248  ERKIntegrate.f90
test               0000000104273624  _MAIN__                   115  test.f90
test               000000010426622E  Unknown               Unknown  Unknown
```

**Comment by princemahajan** [comment]
I just checked with ifort-18.0.2 with all the run-time checks and warnings enabled (standard-2008) and not even seeing any warnings. I need to get my hands on ifort-19 to see what's happening here. Just to make sure, this is how I build it:
cmake -G 'Visual Studio 15 2017" -A x64 -S SRC_DIR -B BUILD_DIR

**Comment by princemahajan** [comment]
Fixed this issue moving a declaration out of the block construct. Not fully sure what exactly was the issue. It may be an issue with ifort-19 but I am not able to reproduce it in a simpler code. Try now.
