### ISSUE TITLE
Suggestion: add flint_ to the name of some public parameters

### ISSUE THREAD

**Issue by CRquantum** [princemahajan/FLINT#12]
Hope all is well bro. 
Not an issue, just a small suggestion. 
Perhaps can add 'flint_' to the name of some public parameters, such as those sp, dp, wp, qp, eps stuff as below. 
So that those public parameters names will not have possible conflicts with other codes using FLINT.
Best regards,
Rong
![image](https://user-images.githubusercontent.com/52009942/175166756-90867999-7c14-4568-9ecb-13b36f0b0f11.png)

**Comment by CRquantum** [comment]
PS. 
This is my new paper's link using FLINT solver, https://arxiv.org/abs/2206.02077
I acknowledged you and many other Fortran guys.
Thank you very much for the great solver.
Wish you all the best!
Rong

**Comment by princemahajan** [comment]
done, closing issue!
