### ISSUE TITLE
Dense Output Accuracy for DOP853 is not 7th order

### ISSUE THREAD

**Issue by PunchesMalone** [princemahajan/FLINT#14]
Hello,

Thanks for writing this package. When attempting to use the DOP853 integrator in dense mode to integrate a Gateway reference orbit in the CR3BP, the dense output does not achieve accuracy better than approx 1.e-6 in terms of the Jacobi constant variation, no matter how high I set the rtol/atol values. When comparing against the SciPy DOP853 implementation, the performance is markedly better, with Jacobi Constant error roughly tracking the rtol setting (see attached figure). I attempted to find the bug myself but I was unsuccessful.

![Figure_2](https://user-images.githubusercontent.com/34415625/202719475-9d7aa13f-73d0-4b58-a598-d1b72bdc7cd2.png)

**Comment by princemahajan** [comment]
Thanks for submitting this potential issue. Is it possible for you to provide a sample code for reproduction?

**Comment by PunchesMalone** [comment]
Hello,

Here's a minimum working example, you can just unzip and compile with the current version of FLINT linked. . . The .py file will make a plot for you.

David

[mwe.zip](https://github.com/princemahajan/FLINT/files/10059657/mwe.zip)

**Comment by princemahajan** [comment]
thanks for submitting your code. Will look into it.

**Comment by princemahajan** [comment]
This issue is fixed. A relatively recent unnecessary code change messed up the interpolation coefficients. See the latest WP test codes.
