### ISSUE TITLE
Hi princemahajan super nice job! Just a quick thing about matmul option issue

### ISSUE THREAD

**Issue by CRquantum** [princemahajan/FLINT#5]
Hi princemahajan, 

Nice nice nice nice super great job! I am about to use your package. 

Just a quick thing, 

I am using the files in your latest folder today. 
The files in the src folder + test_CR3BP.f90 in the test folder.

Now, if I   ''enable the matmul library call'' in visual studio 2017 + Intel OneApi 2021.4, see below,
![Screenshot 2021-10-14 112200](https://user-images.githubusercontent.com/52009942/137374446-195f7e8c-68de-4de2-992b-e3bb1732eca5.png)

Then I build the solution and I got error, 

1>------ Build started: Project: FLINT_test (IFORT), Configuration: Release x64 ------
1>Compiling with Intel® Fortran Compiler Classic 2021.4.0 [Intel(R) 64]...
1>FLINTUtils.f90
1>FLINT_base.f90
1>StepSz.f90
1>ButcherTableaus.f90
1>ERK.f90
1>ERKIntegrate.f90
1>ERKInit.f90
1>FLINT.f90
1>ERKStepInt.f90
1>ERKInterp.f90
1>test_CR3BP.f90
1>Linking...
1>libmatmul.lib(dgemv_matmul.obj) : error LNK2019: unresolved external symbol omp_in_parallel referenced in function matmul_dgemv
1>libmatmul.lib(mkl_threading_patched.obj) : error LNK2001: unresolved external symbol omp_in_parallel
1>libmatmul.lib(dgemv_matmul.obj) : error LNK2019: unresolved external symbol omp_get_max_threads referenced in function matmul_dgemv
1>libmatmul.lib(mkl_threading_patched.obj) : error LNK2001: unresolved external symbol omp_get_max_threads
1>libmatmul.lib(d__gemm_drv.obj) : error LNK2019: unresolved external symbol __kmpc_critical_with_hint referenced in function omp_parallel_acopy_lookahead
1>libmatmul.lib(d__gemm_drv.obj) : error LNK2019: unresolved external symbol __kmpc_end_critical referenced in function omp_parallel_acopy_lookahead
1>libmatmul.lib(d__gemm_drv.obj) : error LNK2019: unresolved external symbol __kmpc_ok_to_fork referenced in function gemm_omp_driver_v2
1>libmatmul.lib(dgemv_omp_matmul.obj) : error LNK2001: unresolved external symbol __kmpc_ok_to_fork
1>libmatmul.lib(d__gemm_omp_v1_drv.obj) : error LNK2001: unresolved external symbol __kmpc_ok_to_fork
1>libmatmul.lib(d__gemm_drv.obj) : error LNK2019: unresolved external symbol __kmpc_push_num_threads referenced in function gemm_omp_driver_v2
1>libmatmul.lib(dgemv_omp_matmul.obj) : error LNK2001: unresolved external symbol __kmpc_push_num_threads
1>libmatmul.lib(d__gemm_omp_v1_drv.obj) : error LNK2001: unresolved external symbol __kmpc_push_num_threads
1>libmatmul.lib(d__gemm_drv.obj) : error LNK2019: unresolved external symbol __kmpc_fork_call referenced in function gemm_omp_driver_v2
1>libmatmul.lib(dgemv_omp_matmul.obj) : error LNK2001: unresolved external symbol __kmpc_fork_call
1>libmatmul.lib(d__gemm_omp_v1_drv.obj) : error LNK2001: unresolved external symbol __kmpc_fork_call
1>libmatmul.lib(d__gemm_drv.obj) : error LNK2019: unresolved external symbol __kmpc_serialized_parallel referenced in function gemm_omp_driver_v2
1>libmatmul.lib(dgemv_omp_matmul.obj) : error LNK2001: unresolved external symbol __kmpc_serialized_parallel
1>libmatmul.lib(d__gemm_omp_v1_drv.obj) : error LNK2001: unresolved external symbol __kmpc_serialized_parallel
1>libmatmul.lib(d__gemm_drv.obj) : error LNK2019: unresolved external symbol __kmpc_end_serialized_parallel referenced in function gemm_omp_driver_v2
1>libmatmul.lib(dgemv_omp_matmul.obj) : error LNK2001: unresolved external symbol __kmpc_end_serialized_parallel
1>libmatmul.lib(d__gemm_omp_v1_drv.obj) : error LNK2001: unresolved external symbol __kmpc_end_serialized_parallel
1>libmatmul.lib(d__gemm_drv.obj) : error LNK2019: unresolved external symbol omp_get_thread_num referenced in function gemm_omp_driver_v2
1>libmatmul.lib(d__gemm_omp_v1_drv.obj) : error LNK2001: unresolved external symbol omp_get_thread_num
1>libmatmul.lib(d__gemm_drv.obj) : error LNK2019: unresolved external symbol omp_get_num_threads referenced in function gemm_omp_driver_v2
1>libmatmul.lib(d__gemm_omp_v1_drv.obj) : error LNK2001: unresolved external symbol omp_get_num_threads
1>libmatmul.lib(dgemv_omp_matmul.obj) : error LNK2019: unresolved external symbol __kmpc_for_static_init_8u referenced in function matmul_dgemv_omp
1>libmatmul.lib(dgemv_omp_matmul.obj) : error LNK2019: unresolved external symbol __kmpc_for_static_fini referenced in function matmul_dgemv_omp
1>libmatmul.lib(dgemv_omp_matmul.obj) : error LNK2019: unresolved external symbol __kmpc_single referenced in function matmul_dgemv_omp
1>libmatmul.lib(d__gemm_omp_v1_drv.obj) : error LNK2001: unresolved external symbol __kmpc_single
1>libmatmul.lib(dgemv_omp_matmul.obj) : error LNK2019: unresolved external symbol __kmpc_end_single referenced in function matmul_dgemv_omp
1>libmatmul.lib(d__gemm_omp_v1_drv.obj) : error LNK2001: unresolved external symbol __kmpc_end_single
1>libmatmul.lib(d__gemm_omp_v1_drv.obj) : error LNK2019: unresolved external symbol __kmpc_barrier referenced in function matmul_mkl_dgemm_omp_driver_v1
1>x64\Release\FLINT_test.exe : fatal error LNK1120: 16 unresolved externals
1>
1>Build log written to  "file://D:\Works%20CHLA\Fortran_test\FLINT_test\FLINT_test\x64\Release\BuildLog.htm"
1>FLINT_test - 33 error(s), 0 warning(s)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
 
it looks like related with openMP or something. Would  you please check? 

Anyway, if I do not enable matmul library call, then no problem. 

Thank you very much. 

Best regards,
Rong

**Comment by CRquantum** [comment]
Right right right, thank you so much! 
Yes with /Qparallel it is runs without any problem! 
Nice nice nice!

**Comment by princemahajan** [comment]
btw note that these combination of optimization flags are making the code actually run slower (at least on my machine).
